# Generated by Django 4.2.3 on 2023-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.AutoField(auto_created=1000, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField(blank=True, null=True)),
                ('loaded_file', models.FileField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
