# Generated by Django 4.2.3 on 2023-07-31 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='image_link',
            new_name='image_url',
        ),
    ]
